In [3]:
import numpy as np
import pandas as pd


In [5]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [6]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [48]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1,L):

    parameters['W' + str(l)] = np.ones((layer_dims[l],layer_dims[l-1]))*0.1
    parameters['b'+ str(l)] = np.zeros((layer_dims[l],1))

  return parameters

In [49]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1, 0.1]]),
 'b2': array([[0.]])}

In [50]:
def linear_forward(A_prev, W, b):

  Z = np.dot(W, A_prev) + b
  return Z

In [51]:
# Forward Propagation
def L_layer_forward(X,parameters):
  A = X
  L = len(parameters)//2

  for l in range(1,L+1):
    A_prev = A
    W1 = parameters['W'+ str(l)]
    b1 = parameters['b'+str(l)]
    print("A"+str(l-1)+":",A_prev)
    print("W"+str(l)+":", W1)
    print("b"+str(l)+":", b1)
    print("--"*20)

    A = linear_forward(A_prev,W1,b1)
    print("A"+str(l)+": ",A)
    print("**"*20)

    return A,A_prev


In [58]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

#parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************


In [59]:
L_layer_forward(X,parameters)



A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************


(array([[1.6],
        [1.6]]),
 array([[8],
        [8]]))

array([[8],
       [8]])

In [57]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W1'][0][0]  = parameters['W2'][0][0]+(0.001 * 2 * (y-y_hat)*A1[0][0])
  parameters['W2'][1][0]  = parameters['W2'][1][0]+(0.001 * 2 * (y-y_hat)*A1[1][0])
  parameters['b1'][0][0]  = parameters['W2'][1][0]+(0.001 * 2 * (y-y_hat))

  parameters['W1'][0][0]  = parameters['W2'][0][0]+(0.001 * 2 * (y-y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1]  = parameters['W2'][0][1]+(0.001 * 2 * (y-y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0]  = parameters['W2'][0][0]+(0.001 * 2 * (y-y_hat))*parameters['W2'][0][0]

  parameters['W1'][1][0]  = parameters['W2'][1][0]+(0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1]  = parameters['W2'][1][1]+(0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0]  = parameters['W2'][1][0]+(0.001 * 2 * (y-y_hat))*parameters['W2'][1][0]




In [ ]:
#epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 3

for i in range (epochs):
  Loss  = []

  for j in range(df.shape[0]):

    X = df[['cgpa','profile_score']].values[j].reshape(2,1)
    y = df[['lpa']].values[j][0]


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('epoch - ', i+1, 'Loss - ', np.array(Loss).mean())

parameters